名字: 葫芦侠_登录
在:
  日程安排:    # 定时触发
    - 时间单位: '0 1,5,10 * * *'  # 24点
  工作流_调度:  # 支持手动触发
工作:
  建设:
    连续运行: Ubuntu-最新版
    步伐:
      - 名字: 检验
        使用: 动作/签出@v3
      - 名字: '初始化大蟒环境'
        使用: 操作/设置-python@v4
        随着:
           大蟒版本: 3.10.11
      - 名字: '安装依赖'
        奔跑: |
点安装-升级点
点安装-r ./requirements.txt
      - 名字: '开始运行'
        身份证明(识别): 登录-输出
        包封/包围（动词包围的简写):
          # 不需要的推送形式可以直接注释，反之你需要取消注释            
          通知者_类型: ${{机密。通知者类型}}
          #EMAIL_CONFIG: ${{ secrets。EMAIL_CONFIG }}
          微信_机器人_网址: ${{机密。微信_机器人_网址}}
          帐目: ${{机密。帐户}}
        奔跑: |
python。/家。巴拉圭
